name: Krav Maga
favicon: null
layout_spectrum: 0.4053851
typography_spectrum: 0.7696025
title: Titan Gym's Krav Maga Program
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3961169
  lightness: 0.4473684
  saturation: 0.02672244
  rhythmicContrast: 0.401114
purpose: []
